// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "explorer_mail.h"

/////////////////////////////////////////////////////////////////////////////
// CExplorer_mail

IMPLEMENT_DYNCREATE(CExplorer_mail, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CExplorer_mail properties

/////////////////////////////////////////////////////////////////////////////
// CExplorer_mail operations
